//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDatabase.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.InspectionImages = new HashSet<InspectionImage>();
            this.Questionaires = new HashSet<Questionaire>();
        }
    
        public long Id { get; set; }
        public long AssignmentId { get; set; }
        public long RegionId { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long StatusId { get; set; }
        public Nullable<long> InspectorId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int ExistsInCentral { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Region Region { get; set; }
        public virtual InspectionStatu InspectionStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionImage> InspectionImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questionaire> Questionaires { get; set; }
    }
}
