//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDatabase.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalParkInspectEntities : DbContext
    {
        public LocalParkInspectEntities()
            : base("name=LocalParkInspectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<Availability> Availability { get; set; }
        public virtual DbSet<Coordinate> Coordinate { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeStatus> EmployeeStatus { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<InspectionImage> InspectionImage { get; set; }
        public virtual DbSet<InspectionStatus> InspectionStatus { get; set; }
        public virtual DbSet<Keyword> Keyword { get; set; }
        public virtual DbSet<KeywordCategory> KeywordCategory { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questionaire> Questionaire { get; set; }
        public virtual DbSet<QuestionaireModule> QuestionaireModule { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswer { get; set; }
        public virtual DbSet<QuestionKeyword> QuestionKeyword { get; set; }
        public virtual DbSet<QuestionSort> QuestionSort { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<WorkingHours> WorkingHours { get; set; }
    }
}
