//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDatabase.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionaireModule
    {
        public long ModuleId { get; set; }
        public long QuestionaireId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int ExistsInCentral { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Questionaire Questionaire { get; set; }
    }
}
