//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspectGroupC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentThemeUri {
            get {
                return ((string)(this["CurrentThemeUri"]));
            }
            set {
                this["CurrentThemeUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnOffline {
            get {
                return ((bool)(this["OnOffline"]));
            }
            set {
                this["OnOffline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LocalDatabase.Domain.Employee LoggedInEmp {
            get {
                return ((global::LocalDatabase.Domain.Employee)(this["LoggedInEmp"]));
            }
            set {
                this["LoggedInEmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyncError {
            get {
                return ((bool)(this["SyncError"]));
            }
            set {
                this["SyncError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long QuestionnaireSelectedInspectionId {
            get {
                return ((long)(this["QuestionnaireSelectedInspectionId"]));
            }
            set {
                this["QuestionnaireSelectedInspectionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long AssignmentId {
            get {
                return ((long)(this["AssignmentId"]));
            }
            set {
                this["AssignmentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long InspectionRegionId {
            get {
                return ((long)(this["InspectionRegionId"]));
            }
            set {
                this["InspectionRegionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long InspectionAssignmentId {
            get {
                return ((long)(this["InspectionAssignmentId"]));
            }
            set {
                this["InspectionAssignmentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long InspectionStatusId {
            get {
                return ((long)(this["InspectionStatusId"]));
            }
            set {
                this["InspectionStatusId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long InspectionInspectorId {
            get {
                return ((long)(this["InspectionInspectorId"]));
            }
            set {
                this["InspectionInspectorId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InspectionLocation {
            get {
                return ((string)(this["InspectionLocation"]));
            }
            set {
                this["InspectionLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime InspectionStartDatum {
            get {
                return ((global::System.DateTime)(this["InspectionStartDatum"]));
            }
            set {
                this["InspectionStartDatum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime InspectionEindDatum {
            get {
                return ((global::System.DateTime)(this["InspectionEindDatum"]));
            }
            set {
                this["InspectionEindDatum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long InspectionId {
            get {
                return ((long)(this["InspectionId"]));
            }
            set {
                this["InspectionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LocalDatabase.Domain.Employee Employee {
            get {
                return ((global::LocalDatabase.Domain.Employee)(this["Employee"]));
            }
            set {
                this["Employee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LocalDatabase.Domain.Availability Availability {
            get {
                return ((global::LocalDatabase.Domain.Availability)(this["Availability"]));
            }
            set {
                this["Availability"] = value;
            }
        }
    }
}