:r .\AccountPost.sql
:r .\CustomerPost.sql
:r .\RegionPost.sql
:r .\EmployeeStatusPost.sql
:r .\InspectionStatusPost.sql
:r .\EmployeePost.sql
:r .\AssignmentPost.sql
:r .\WorkingHoursPost.sql
--:r .\QuestionsPost.sql