
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspectGroupC.DOMAIN
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Account = new HashSet<Account>();

        this.Assignment = new HashSet<Assignment>();

        this.Inspection = new HashSet<Inspection>();

        this.Employees = new HashSet<Employee>();

        this.Availabilities = new HashSet<Availability>();

        this.WorkingHours = new HashSet<WorkingHour>();

    }


    public int Id { get; set; }

    public string FirstName { get; set; }

    public string Prefix { get; set; }

    public string SurName { get; set; }

    public string Gender { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string ZipCode { get; set; }

    public string Phonenumber { get; set; }

    public string Email { get; set; }

    public Nullable<int> RegionId { get; set; }

    public Nullable<int> EmployeeStatusId { get; set; }

    public System.DateTime DateCreated { get; set; }

    public System.DateTime DateUpdated { get; set; }

    public bool IsInspecter { get; set; }

    public bool IsManager { get; set; }

    public Nullable<int> ManagerId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Account> Account { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Assignment> Assignment { get; set; }

    public virtual EmployeeStatus EmployeeStatus { get; set; }

    public virtual Region Region { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Inspection> Inspection { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Employees { get; set; }

    public virtual Employee Manager { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Availability> Availabilities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkingHour> WorkingHours { get; set; }

}

}
