//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspectGroupC.DOMAIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionImage
    {
        public int Id { get; set; }
        public string File { get; set; }
        public Nullable<int> InspectionId { get; set; }
    
        public virtual Inspection Inspection { get; set; }
    }
}
